from mosi.settings.common import *

SECRET_KEY = 'CHANGE_THIS'
SECURITY_PASSWORD_SALT = 'SOME_SALT'

RECAPTCHA_PUBLIC_KEY = 'CHANGE_THIS'
RECAPTCHA_PRIVATE_KEY = 'CHANGE_THIS'

SQLALCHEMY_DATABASE_URI = 'postgresql://postgres:password@localhost:5432/lobe_dev_db_6'

TAL_API_TOKEN = 'YOUR_TAL_API_TOKEN'

DEBUG = True
FLASK_DEBUG = True
