from mosi.settings.common import *

SECRET_KEY = 'CHANGE_THIS'
SECURITY_PASSWORD_SALT = 'SOME_SALT'

RECAPTCHA_PUBLIC_KEY = 'CHANGE_THIS'
RECAPTCHA_PRIVATE_KEY = 'CHANGE_THIS'

SQLALCHEMY_DATABASE_URI = 'postgresql://POSTGRES_USER:POSTGRES_PASSWORD@localhost:POSTGRES_PORT/POSTGRES_DB_NAME'

TAL_API_TOKEN = 'YOUR_TAL_API_TOKEN'

DEBUG = True
FLASK_DEBUG = True
