"""empty message

Revision ID: 1bd403738501
Revises: cb4f59fdb81a
Create Date: 2021-10-26 14:56:36.934766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bd403738501'
down_revision = 'cb4f59fdb81a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('CustomToken', 'fname')
    op.drop_column('CustomToken', 'copied_token')
    op.drop_column('CustomToken', 'path')
    op.drop_column('CustomToken', 'original_fname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CustomToken', sa.Column('original_fname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('CustomToken', sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('CustomToken', sa.Column('copied_token', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('CustomToken', sa.Column('fname', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
