"""empty message

Revision ID: 27b686714f50
Revises: a36f33702199
Create Date: 2022-01-06 20:25:49.162280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27b686714f50'
down_revision = 'a36f33702199'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Sus',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('question', sa.String(), nullable=True),
    sa.Column('form_text', sa.String(), nullable=True),
    sa.Column('help_text', sa.String(), nullable=True),
    sa.Column('done_text', sa.String(), nullable=True),
    sa.Column('num_samples', sa.Integer(), nullable=True),
    sa.Column('num_participants', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('SusObject',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sus_id', sa.Integer(), nullable=True),
    sa.Column('is_synth', sa.Boolean(), nullable=True),
    sa.Column('voice_idx', sa.Integer(), nullable=True),
    sa.Column('utterance_idx', sa.Integer(), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('selected', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['sus_id'], ['Sus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('CustomRecording', sa.Column('sus_object_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'CustomRecording', 'SusObject', ['sus_object_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'CustomRecording', type_='foreignkey')
    op.drop_column('CustomRecording', 'sus_object_id')
    op.drop_table('SusObject')
    op.drop_table('Sus')
    # ### end Alembic commands ###
