"""empty message

Revision ID: 2ed03db70748
Revises: bdc652649cfb
Create Date: 2022-08-26 14:55:32.424800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ed03db70748'
down_revision = 'bdc652649cfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Sus', sa.Column('max_listens', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Sus', 'max_listens')
    # ### end Alembic commands ###
