"""empty message

Revision ID: 2f145aed69cf
Revises: 27b686714f50
Create Date: 2022-01-12 16:07:40.718995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f145aed69cf'
down_revision = '27b686714f50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ABtest', sa.Column('num_listening_samples_per_test', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ABtest', 'num_listening_samples_per_test')
    # ### end Alembic commands ###
