"""empty message

Revision ID: 354dedb0dfb0
Revises: 5b80c1273929
Create Date: 2021-10-19 14:31:50.964195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '354dedb0dfb0'
down_revision = '5b80c1273929'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ABTuple',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('abtest_id', sa.Integer(), nullable=True),
    sa.Column('ab_instance_first_id', sa.Integer(), nullable=True),
    sa.Column('ab_instance_second_id', sa.Integer(), nullable=True),
    sa.Column('ab_instance_referance_id', sa.Integer(), nullable=True),
    sa.Column('placement', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ab_instance_first_id'], ['ABInstance.id'], ),
    sa.ForeignKeyConstraint(['ab_instance_referance_id'], ['ABInstance.id'], ),
    sa.ForeignKeyConstraint(['ab_instance_second_id'], ['ABInstance.id'], ),
    sa.ForeignKeyConstraint(['abtest_id'], ['ABtest.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ab_instance_first_id', 'ab_instance_second_id', 'ab_instance_referance_id')
    )
    op.add_column('ABRating', sa.Column('ab_tuple_id', sa.Integer(), nullable=True))
    op.drop_constraint('ABRating_ab_instance_first_id_ab_instance_second_id_user_id_key', 'ABRating', type_='unique')
    op.create_unique_constraint(None, 'ABRating', ['ab_tuple_id', 'user_id'])
    op.drop_constraint('ABRating_ab_instance_second_id_fkey', 'ABRating', type_='foreignkey')
    op.drop_constraint('ABRating_ab_instance_first_id_fkey', 'ABRating', type_='foreignkey')
    op.drop_constraint('ABRating_ab_instance_referance_id_fkey', 'ABRating', type_='foreignkey')
    op.create_foreign_key(None, 'ABRating', 'ABTuple', ['ab_tuple_id'], ['id'])
    op.drop_column('ABRating', 'placement')
    op.drop_column('ABRating', 'ab_instance_second_id')
    op.drop_column('ABRating', 'ab_instance_first_id')
    op.drop_column('ABRating', 'ab_instance_referance_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ABRating', sa.Column('ab_instance_referance_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ABRating', sa.Column('ab_instance_first_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ABRating', sa.Column('ab_instance_second_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ABRating', sa.Column('placement', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ABRating', type_='foreignkey')
    op.create_foreign_key('ABRating_ab_instance_referance_id_fkey', 'ABRating', 'ABInstance', ['ab_instance_referance_id'], ['id'])
    op.create_foreign_key('ABRating_ab_instance_first_id_fkey', 'ABRating', 'ABInstance', ['ab_instance_first_id'], ['id'])
    op.create_foreign_key('ABRating_ab_instance_second_id_fkey', 'ABRating', 'ABInstance', ['ab_instance_second_id'], ['id'])
    op.drop_constraint(None, 'ABRating', type_='unique')
    op.create_unique_constraint('ABRating_ab_instance_first_id_ab_instance_second_id_user_id_key', 'ABRating', ['ab_instance_first_id', 'ab_instance_second_id', 'user_id'])
    op.drop_column('ABRating', 'ab_tuple_id')
    op.drop_table('ABTuple')
    # ### end Alembic commands ###
