"""empty message

Revision ID: 5b80c1273929
Revises: b6c6f9c303c6
Create Date: 2021-10-08 18:21:26.925104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b80c1273929'
down_revision = 'b6c6f9c303c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ABInstance', sa.Column('is_reference', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ABInstance', 'is_reference')
    # ### end Alembic commands ###
