"""empty message

Revision ID: 76ebc1d10441
Revises: 
Create Date: 2021-09-05 17:56:18.809162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76ebc1d10441'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ABtest',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('question', sa.String(), nullable=True),
    sa.Column('form_text', sa.String(), nullable=True),
    sa.Column('help_text', sa.String(), nullable=True),
    sa.Column('done_text', sa.String(), nullable=True),
    sa.Column('show_text_in_test', sa.Boolean(), nullable=True),
    sa.Column('num_samples', sa.Integer(), nullable=True),
    sa.Column('num_participants', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ABInstance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('abtest_id', sa.Integer(), nullable=True),
    sa.Column('is_synth', sa.Boolean(), nullable=True),
    sa.Column('voice_idx', sa.Integer(), nullable=True),
    sa.Column('utterance_idx', sa.Integer(), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('selected', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['abtest_id'], ['ABtest.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ABRating',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('ab_instance_first_id', sa.Integer(), nullable=True),
    sa.Column('ab_instance_second_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('placement', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ab_instance_first_id'], ['ABInstance.id'], ),
    sa.ForeignKeyConstraint(['ab_instance_second_id'], ['ABInstance.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ab_instance_first_id', 'ab_instance_second_id', 'user_id')
    )
    op.add_column('CustomRecording', sa.Column('AB_instance_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'CustomRecording', 'ABInstance', ['AB_instance_id'], ['id'])
    op.add_column('CustomToken', sa.Column('ab_instance_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'CustomToken', 'ABInstance', ['ab_instance_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'CustomToken', type_='foreignkey')
    op.drop_column('CustomToken', 'ab_instance_id')
    op.drop_constraint(None, 'CustomRecording', type_='foreignkey')
    op.drop_column('CustomRecording', 'AB_instance_id')
    op.drop_table('ABRating')
    op.drop_table('ABInstance')
    op.drop_table('ABtest')
    # ### end Alembic commands ###
