"""empty message

Revision ID: 79e1c3bb83e6
Revises: 
Create Date: 2021-11-23 19:30:53.217700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79e1c3bb83e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ABtest',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('question', sa.String(), nullable=True),
    sa.Column('form_text', sa.String(), nullable=True),
    sa.Column('help_text', sa.String(), nullable=True),
    sa.Column('done_text', sa.String(), nullable=True),
    sa.Column('show_text_in_test', sa.Boolean(), nullable=True),
    sa.Column('num_samples', sa.Integer(), nullable=True),
    sa.Column('num_participants', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Configuration',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('session_sz', sa.Integer(), nullable=True),
    sa.Column('live_transcribe', sa.Boolean(), nullable=True),
    sa.Column('visualize_mic', sa.Boolean(), nullable=True),
    sa.Column('auto_trim', sa.Boolean(), nullable=True),
    sa.Column('analyze_sound', sa.Boolean(), nullable=True),
    sa.Column('auto_gain_control', sa.Boolean(), nullable=True),
    sa.Column('noise_suppression', sa.Boolean(), nullable=True),
    sa.Column('channel_count', sa.Integer(), nullable=True),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('blob_slice', sa.Integer(), nullable=True),
    sa.Column('audio_codec', sa.String(), nullable=True),
    sa.Column('video_w', sa.Integer(), nullable=True),
    sa.Column('video_h', sa.Integer(), nullable=True),
    sa.Column('video_codec', sa.String(), nullable=True),
    sa.Column('has_video', sa.Boolean(), nullable=True),
    sa.Column('trim_threshold', sa.Float(), nullable=True),
    sa.Column('too_low_threshold', sa.Float(), nullable=True),
    sa.Column('too_high_threshold', sa.Float(), nullable=True),
    sa.Column('too_high_frames', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('CustomToken',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('marked_as_bad', sa.Boolean(), nullable=True),
    sa.Column('pron', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Mos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('question', sa.String(), nullable=True),
    sa.Column('form_text', sa.String(), nullable=True),
    sa.Column('help_text', sa.String(), nullable=True),
    sa.Column('done_text', sa.String(), nullable=True),
    sa.Column('use_latin_square', sa.Boolean(), nullable=True),
    sa.Column('show_text_in_test', sa.Boolean(), nullable=True),
    sa.Column('num_samples', sa.Integer(), nullable=True),
    sa.Column('num_participants', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('sex', sa.String(length=255), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('dialect', sa.String(length=255), nullable=True),
    sa.Column('audio_setup', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('ABInstance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('abtest_id', sa.Integer(), nullable=True),
    sa.Column('is_reference', sa.Boolean(), nullable=True),
    sa.Column('is_synth', sa.Boolean(), nullable=True),
    sa.Column('voice_idx', sa.Integer(), nullable=True),
    sa.Column('utterance_idx', sa.Integer(), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['abtest_id'], ['ABtest.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('MosInstance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mos_id', sa.Integer(), nullable=True),
    sa.Column('is_synth', sa.Boolean(), nullable=True),
    sa.Column('voice_idx', sa.Integer(), nullable=True),
    sa.Column('utterance_idx', sa.Integer(), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('selected', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['mos_id'], ['Mos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('ABTuple',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('abtest_id', sa.Integer(), nullable=True),
    sa.Column('ab_instance_first_id', sa.Integer(), nullable=True),
    sa.Column('ab_instance_second_id', sa.Integer(), nullable=True),
    sa.Column('ab_instance_referance_id', sa.Integer(), nullable=True),
    sa.Column('selected', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['ab_instance_first_id'], ['ABInstance.id'], ),
    sa.ForeignKeyConstraint(['ab_instance_referance_id'], ['ABInstance.id'], ),
    sa.ForeignKeyConstraint(['ab_instance_second_id'], ['ABInstance.id'], ),
    sa.ForeignKeyConstraint(['abtest_id'], ['ABtest.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ab_instance_first_id', 'ab_instance_second_id', 'ab_instance_referance_id')
    )
    op.create_table('CustomRecording',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('original_fname', sa.String(), nullable=True),
    sa.Column('token_id', sa.Integer(), nullable=True),
    sa.Column('mos_instance_id', sa.Integer(), nullable=True),
    sa.Column('AB_instance_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('copied_recording', sa.Boolean(), nullable=True),
    sa.Column('fname', sa.String(), nullable=True),
    sa.Column('file_id', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('wav_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['AB_instance_id'], ['ABInstance.id'], ),
    sa.ForeignKeyConstraint(['mos_instance_id'], ['MosInstance.id'], ),
    sa.ForeignKeyConstraint(['token_id'], ['CustomToken.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('MosRating',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('mos_instance_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('placement', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mos_instance_id'], ['MosInstance.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mos_instance_id', 'user_id')
    )
    op.create_table('ABRating',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('ab_tuple_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('placement', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ab_tuple_id'], ['ABTuple.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ab_tuple_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ABRating')
    op.drop_table('MosRating')
    op.drop_table('CustomRecording')
    op.drop_table('ABTuple')
    op.drop_table('roles_users')
    op.drop_table('MosInstance')
    op.drop_table('ABInstance')
    op.drop_table('user')
    op.drop_table('role')
    op.drop_table('Mos')
    op.drop_table('CustomToken')
    op.drop_table('Configuration')
    op.drop_table('ABtest')
    # ### end Alembic commands ###
