"""empty message

Revision ID: ae47fede00d2
Revises: 354dedb0dfb0
Create Date: 2021-10-19 15:28:16.145669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae47fede00d2'
down_revision = '354dedb0dfb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ABRating', sa.Column('placement', sa.Integer(), nullable=True))
    op.drop_column('ABTuple', 'placement')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ABTuple', sa.Column('placement', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('ABRating', 'placement')
    # ### end Alembic commands ###
