"""empty message

Revision ID: b6c6f9c303c6
Revises: 76ebc1d10441
Create Date: 2021-09-05 17:58:13.380292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6c6f9c303c6'
down_revision = '76ebc1d10441'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ABRating', sa.Column('ab_instance_referance_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ABRating', 'ABInstance', ['ab_instance_referance_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ABRating', type_='foreignkey')
    op.drop_column('ABRating', 'ab_instance_referance_id')
    # ### end Alembic commands ###
