"""empty message

Revision ID: bdc652649cfb
Revises: 578746ea5d5d
Create Date: 2022-07-28 13:58:44.647556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdc652649cfb'
down_revision = '578746ea5d5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SusAnswer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('answer', sa.String(), nullable=True),
    sa.Column('sus_object_id', sa.Integer(), nullable=True),
    sa.Column('correct_Answer', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sus_object_id'], ['SusObject.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sus_object_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SusAnswer')
    # ### end Alembic commands ###
