"""empty message

Revision ID: bfe63acb5103
Revises: ae47fede00d2
Create Date: 2021-10-19 17:10:21.509894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfe63acb5103'
down_revision = 'ae47fede00d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ABTuple', sa.Column('selected', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ABTuple', 'selected')
    # ### end Alembic commands ###
