"""empty message

Revision ID: c557d7162726
Revises: 5672e7e5ae4f
Create Date: 2022-09-20 15:05:39.707449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c557d7162726'
down_revision = '5672e7e5ae4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Mos', sa.Column('display_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Mos', 'display_name')
    # ### end Alembic commands ###
