"""empty message

Revision ID: cb4f59fdb81a
Revises: bfe63acb5103
Create Date: 2021-10-25 18:46:45.773836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb4f59fdb81a'
down_revision = 'bfe63acb5103'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ABInstance', 'selected')
    op.add_column('CustomRecording', sa.Column('token_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'CustomRecording', 'CustomToken', ['token_id'], ['id'])
    op.drop_constraint('CustomToken_mos_instance_id_fkey', 'CustomToken', type_='foreignkey')
    op.drop_constraint('CustomToken_ab_instance_id_fkey', 'CustomToken', type_='foreignkey')
    op.drop_column('CustomToken', 'mos_instance_id')
    op.drop_column('CustomToken', 'ab_instance_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CustomToken', sa.Column('ab_instance_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('CustomToken', sa.Column('mos_instance_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('CustomToken_ab_instance_id_fkey', 'CustomToken', 'ABInstance', ['ab_instance_id'], ['id'])
    op.create_foreign_key('CustomToken_mos_instance_id_fkey', 'CustomToken', 'MosInstance', ['mos_instance_id'], ['id'])
    op.drop_constraint(None, 'CustomRecording', type_='foreignkey')
    op.drop_column('CustomRecording', 'token_id')
    op.add_column('ABInstance', sa.Column('selected', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
