"""empty message

Revision ID: d00d112a078f
Revises: 868005c9841f
Create Date: 2022-09-19 14:15:54.555409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd00d112a078f'
down_revision = '868005c9841f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MosInstance', sa.Column('model_idx', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('MosInstance', 'model_idx')
    # ### end Alembic commands ###
