"""empty message

Revision ID: e161b722a4e6
Revises: d00d112a078f
Create Date: 2022-09-19 16:44:05.606417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e161b722a4e6'
down_revision = 'd00d112a078f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MosInstance', sa.Column('voice_id', sa.String(length=30), nullable=True))
    op.alter_column('MosInstance', 'model_idx',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('MosInstance', 'model_idx',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_column('MosInstance', 'voice_id')
    # ### end Alembic commands ###
